# Generated by Django 2.2.2 on 2019-06-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190620_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winery',
            old_name='red',
            new_name='grapes',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='white',
        ),
    ]
