# Generated by Django 2.2 on 2019-06-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190620_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winery',
            name='red',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='white',
        ),
        migrations.AddField(
            model_name='winery',
            name='grapes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
