# Generated by Django 2.2.2 on 2019-06-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190620_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winery',
            name='grapes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
