# Generated by Django 2.2 on 2019-06-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190617_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winery',
            name='cave',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='city',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='tours',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='website',
        ),
    ]
