# Generated by Django 2.2 on 2019-06-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190617_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winery',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
